# TCL File Generated by Component Editor 17.0
# Wed May 06 10:35:50 CEST 2020
# DO NOT MODIFY


# 
# AXI4_lite_perso "AXI_Spinelli" v1.0
# Spinelli Isaia 2020.05.06.10:35:50
# Permet de créer une itnerface pour gérer les différents I/O de la FPGA
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AXI4_lite_perso
# 
set_module_property DESCRIPTION "Permet de créer une itnerface pour gérer les différents I/O de la FPGA"
set_module_property NAME AXI4_lite_perso
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Spinelli Isaia"
set_module_property DISPLAY_NAME AXI_Spinelli
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi4lite_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi4lite_slave.vhd VHDL PATH ../../../IP_axi4lite_interface/src/axi4lite_slave.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AXI_DATA_WIDTH INTEGER 32
set_parameter_property AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property AXI_DATA_WIDTH DISPLAY_NAME AXI_DATA_WIDTH
set_parameter_property AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property AXI_DATA_WIDTH UNITS None
set_parameter_property AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter AXI_ADDR_WIDTH INTEGER 12
set_parameter_property AXI_ADDR_WIDTH DEFAULT_VALUE 12
set_parameter_property AXI_ADDR_WIDTH DISPLAY_NAME AXI_ADDR_WIDTH
set_parameter_property AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property AXI_ADDR_WIDTH UNITS None
set_parameter_property AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock clock_sink
set_interface_property altera_axi4lite_slave associatedReset reset_sink
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave axi_araddr_i araddr Input axi_addr_width
add_interface_port altera_axi4lite_slave axi_arprot_i arprot Input 3
add_interface_port altera_axi4lite_slave axi_arready_o arready Output 1
add_interface_port altera_axi4lite_slave axi_arvalid_i arvalid Input 1
add_interface_port altera_axi4lite_slave axi_awaddr_i awaddr Input axi_addr_width
add_interface_port altera_axi4lite_slave axi_awprot_i awprot Input 3
add_interface_port altera_axi4lite_slave axi_awready_o awready Output 1
add_interface_port altera_axi4lite_slave axi_awvalid_i awvalid Input 1
add_interface_port altera_axi4lite_slave axi_bready_i bready Input 1
add_interface_port altera_axi4lite_slave axi_bresp_o bresp Output 2
add_interface_port altera_axi4lite_slave axi_bvalid_o bvalid Output 1
add_interface_port altera_axi4lite_slave axi_rdata_o rdata Output axi_data_width
add_interface_port altera_axi4lite_slave axi_rready_i rready Input 1
add_interface_port altera_axi4lite_slave axi_rresp_o rresp Output 2
add_interface_port altera_axi4lite_slave axi_rvalid_o rvalid Output 1
add_interface_port altera_axi4lite_slave axi_wdata_i wdata Input axi_data_width
add_interface_port altera_axi4lite_slave axi_wready_o wready Output 1
add_interface_port altera_axi4lite_slave axi_wstrb_i wstrb Input axi_data_width/8
add_interface_port altera_axi4lite_slave axi_wvalid_i wvalid Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink axi_clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink axi_reset_i reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end switch_i switch_i Input axi_data_width
add_interface_port conduit_end key_i key_i Input axi_data_width
add_interface_port conduit_end leds_o leds_o Output axi_data_width
add_interface_port conduit_end hex0_o hex0_o Output axi_data_width
add_interface_port conduit_end hex1_o hex1_o Output axi_data_width
add_interface_port conduit_end hex2_o hex2_o Output axi_data_width
add_interface_port conduit_end hex3_o hex3_o Output axi_data_width
add_interface_port conduit_end hex4_o hex4_o Output axi_data_width
add_interface_port conduit_end hex5_o hex5_o Output axi_data_width


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq_o irq Output 1

